# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('agente_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('supervisor_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_estado', models.CharField(choices=[('a', 'Abierto'), ('p', 'Pendiente'), ('c', 'Cerrado')], default='a', max_length=200)),
            ],
        ),
    ]
