# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMasterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TicketMasterApp.Agente'),
            preserve_default=False,
        ),
    ]
